[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
bevy = { version = "0.17", default-features = false, features = [
  "multi_threaded"
] }
lightyear = { workspace = true }
mlua = { workspace = true }
